ALTER INDEX ALL ON SOCIOS DISABLE;


BULK INSERT SOCIOS
FROM 'D:\SQLServer\Imports\DATA_LIMPIA_GIMNASIO1.csv'
WITH (
    FIRSTROW = 2, -- Si tu CSV tiene encabezados
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK
);

ALTER INDEX ALL ON SOCIOS REBUILD;
