  
USE GIM

CREATE INDEX IX_SOCIOS_Covering_Pagos
ON dbo.SOCIOS (ID_SOCIOS_AP) 
INCLUDE (NOMBRE, TELEFONO );


CREATE INDEX IX_PAGOS_ConsultaEficaz
ON dbo.PAGOS (ID_SOCIOS_AP, MES DESC);

CREATE NONCLUSTERED INDEX IX_SOCIOS_NombreTelefono 
ON dbo.SOCIOS (NOMBRE, TELEFONO);

CREATE NONCLUSTERED INDEX IX_PAGOS_Estadisticas_Mensuales
ON dbo.PAGOS (AÑO, MES)
INCLUDE (monto);

